### ISSUE TITLE
HP Pot Error with Caali's Tera Proxy

### ISSUE THREAD

**Issue by LeandraTS** [Fukki/auto-pot#1]
Hi there,
Started to get this error since proxy got updated yesterday.

`ERROR tera-proxy-game: [dispatch] handle: failed to parse S_USER_STATUS<1>
hook: (anonymous) in auto-pot-master
data: 1100076125670910008000030000000000
error: version 1 of message (name: "S_USER_STATUS", code: 24839) is outdated and cannot be used anymore
    at TeraProtocol.resolveIdentifier (Y:\CaaliTeraProxy2\node_modules\tera-data-parser\lib\protocol\index.js:110:15)
    at TeraProtocol.parse (Y:\CaaliTeraProxy2\node_modules\tera-data-parser\lib\protocol\index.js:342:12)`

Mana seems to activate ok, but HP doesn't.

Also, how do I mod it to make HP & MP pots activate outside of combat so both are always kept almost to max?

Many thanks in advance for any fixes / help you can give when able to.

**Comment by Fukki** [comment]
should be not error now @_@

**Comment by LeandraTS** [comment]
Thank you for fixing first error but sorry to say there is another error now.

I re-installed the proxy just to make sure, and downloaded new version of auto-pot from this repository, logged into tera, and got this error message before doing anything.

`ERROR tera-proxy-game: [dispatch] handle: error running hook for S_USER_STATUS<3>
hook: (anonymous) in auto-pot-master
data: { gameId: 360428707947027236n, status: 2, bySkill: false }
error: Cannot read property 'equals' of undefined
    at Object.AutoPOT.mod.hook.e [as callback] (Y:\CaaliTeraProxy2\bin\node_modules\auto-pot-master\index.js:80:50)
