### ISSUE TITLE
Unable to auto-update

### ISSUE THREAD

**Issue by aesarea** [Fukki/auto-pot#10]
[17:22:46.146] [update] ERROR: Unable to auto-update module AutoPOT:
[17:22:46.148] Failed to update the following module files:
 - index.js
 - ERROR: https://raw.githubusercontent.com/Fukki/auto-pot/master/index.js
Downloaded file doesn't match hash specified in patch manifest! Possible causes:
   + Incorrect manifest specified by module developer
   + NoPing (if you're using it) has a bug that can fuck up the download

**Comment by Fukki** [comment]
fixed maybe problem in hash file
