### ISSUE TITLE
Anyone have opcode for s_inven ?

### ISSUE THREAD

**Issue by AntiScrewdriver** [Fukki/auto-pot#18]
![image](https://user-images.githubusercontent.com/47073195/64072381-6f635700-cce1-11e9-86b2-1a66c413e7a5.png)
 
Anyone have opcode for s_inven ? NA 85.6

**Comment by Fukki** [comment]
usually S_INVEN should has opcode
check your proxy update

**Comment by Fukki** [comment]
fixed
