### ISSUE TITLE
can you fix this please - eu / caali's proxy

### ISSUE THREAD

**Issue by Teramystic** [Fukki/auto-pot#19]
![image](https://user-images.githubusercontent.com/51515860/64074993-0f59ba00-ccbb-11e9-9553-41b773e956b5.png)

**Comment by Fukki** [comment]
unmapped packet is not my fault.
check your proxy update.

**Comment by Fukki** [comment]
ok i found problem now

**Comment by Fukki** [comment]
look like patch 85 not have S_INVEN
