### ISSUE TITLE
New error after last update

### ISSUE THREAD

**Issue by LeandraTS** [Fukki/auto-pot#2]
Thank you for fixing first error but sorry to say there is another error now.

I re-installed the proxy just to make sure, and downloaded new version of auto-pot from this repository, logged into tera, and got this error message before doing anything.

`ERROR tera-proxy-game: [dispatch] handle: error running hook for S_USER_STATUS<3>
hook: (anonymous) in auto-pot-master
data: { gameId: 360428707947027236n, status: 2, bySkill: false }
error: Cannot read property 'equals' of undefined
at Object.AutoPOT.mod.hook.e [as callback] (Y:\CaaliTeraProxy2\bin\node_modules\auto-pot-master\index.js:80:50)

**Comment by Fukki** [comment]
Fixed restart for auto-update :x
