### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gzosiek21** [Fukki/auto-pot#20]
[00:13:08.044] [dispatch] [autopot] handle: error running raw hook for S_ITEMLIST<raw>
hook: (anonymous) in autopot
data: 340cdb5d0f003100881626000080000200000000010000000200000010000000b56fd777000000000000000000000100013100fe00000000000200c60000000000c400655f0200b92a810300000000a803000000000000050000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff0000000000000000000000000000000000c600e200000000000000000000000000000000000000000000000000e2000000000000000100000000000000000000000000000000000000fe00cb010000000002009301000000009101bc0100007673c10500000000a8030000000000000c0000003700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff00000000000000000000000000000000009301af01000000000000000000000000000000000000000000000000af010000000000000100000000000000000000000000000000000000cb0198020000000002006002000000005e02054c02003b74c10500000000a8030000000000000d0000001a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff000000000000000000000000000000000060027c020000000000000000000000000000000000000000000000007c020000000000000100000000000000000000000000000000000000980265030000000002002d03000000002b0347550200aa75c10500000000a8030000000000000b0000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff00000000000000000000000000000000002d0349030000000000000000000000000000000000000000000000004903000000000000010000000000000000000000000000000000000065033204000000000200fa0300000000f803da100300b075c10500000000a803000000000000090000002f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff0000000000000000000000000000000000fa031604000000000000000000000000000000000000000000000000160400000000000001000000000000000000000000000000000000003204ff04000000000200c70400000000c5040f4c02002776c10500000000a803000000000000030000001200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff0000000000000000000000000000000000c704e304000000000000000000000000000000000000000000000000e3040000000000000100000000000000000000000000000000000000ff04cc050000000002009405000000009205074c02002876c10500000000a803000000000000040000004500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff00000000000000000000000000000000009405b005000000000000000000000000000000000000000000000000b0050000000000000100000000000000000000000000000000000000cc0599060000000002006106000000005f061f150300a354f31000000000a8030000000000000f0000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff000000000000000000000000000000000061067d060000000000000000000000000000000000000000000000007d060000000000000100000000000000000000000000000000000000990666070000000002002e07000000002c07140500009111171100000000a803000000000000070000000c06000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff00000000000000000000000000000000002e074a070000000000000000000000000000000000000000000000004a07000000000000010000000000000000000000000000000000000066073308000000000200fb0700000000f9071505000019df171100000000a803000000000000060000006400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff0000000000000000000000000000000000fb0717080000000000000000000000000000000000000000000000001708000000000000010000000000000000000000000000000000000033080009000000000200c80800000000c6083c3d0100c640201100000000a8030000000000000a0000004001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff0000000000000000000000000000000000c808e408000000000000000000000000000000000000000000000000e40800000000000001000000000000000000000000000000000000000009cd0900000000020095090000000093090e4c0200af46271100000000a8030000000000000e0000000600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff00000000000000000000000000000000009509b109000000000000000000000000000000000000000000000000b1090000000000000100000000000000000000000000000000000000cd099a0a000000000200620a00000000600a6c8101007125291100000000a803000000000000010000006e06000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff0000000000000000000000000000000000620a7e0a0000000000000000000000000000000000000000000000007e0a00000000000001000000000000000000000000000000000000009a0a670b0000000002002f0b000000002d0b6a8101007725291100000000a80300000000000002000000f504000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff00000000000000000000000000000000002f0b4b0b0000000000000000000000000000000000000000000000004b0b0000000000000100000000000000000000000000000000000000670b0000000000000200fc0b00000000fa0bd2240300d69e5f1100000000a803000000000000080000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff0000000000000000000000000000000000fc0b180c000000000000000000000000000000000000000000000000180c0000000000000100000000000000000000000000000000000000
error: e is not defined
    at Object.callback (C:\Users\opopoAppData\Local\Programs\TeraToolbox\mods\auto-pot-master\index.js:236:22)

**Comment by AntiScrewdriver** [comment]
Same here error on both Teratoolbox and Pinkipi's Proxy. Playing on NA, both proxies updated, (fresh download and auto updates on)

**Comment by Fukki** [comment]
maybe fixed
because i'm not playing tera now
and not testing module :x
