### ISSUE TITLE
Another long.js error + problem

### ISSUE THREAD

**Issue by LeandraTS** [Fukki/auto-pot#3]
Hi again,
Sorry to keep bothering you but thought I'd let you know about the error.

error message:
DeprecationWarning: Long.JS is deprecated. Use BigInt equivalents instead.
    at Object.AutoPOT.mod.hook.e [as callback] (Y:\CaaliTeraProxy\bin\node_modules\auto-pot-master\index.js:80:50)

Also:
When I try to change the percentages at which the mp and hp kick in, they constantly reset back to the defaults, 

Since tera lags badly I really need the hp at 90% and mp at 80% so it always up.

And is there anyway to set both hp and mp to work without being in combat? as on mystic most of her healing skills don't activate the hp node combat requirement so an option to make both non combat would be a huge help to keep her alive in bad parties.

Many thanks for all your hard work.

**Comment by Fukki** [comment]
Hi, what is version you use that
i did get any error after done step
i think you are in "nextGen" version
many require file are problem

for combat feature i will added after

**Comment by LeandraTS** [comment]
the error now gone, it updated after your message.
and just wanted to add, really appreciate all the work you put into the add-on, am sure I speak for many when I say it is very much appreciated.
