### ISSUE TITLE
cd is used instead of amount

### ISSUE THREAD

**Issue by Foks5000** [Fukki/auto-pot#7]
Attempts to use the potion even if it is not in the inventory. The countdown starts from 9, then stops.
![image](https://user-images.githubusercontent.com/2840949/51433569-ef7c0580-1c98-11e9-881f-4a2e032b6eac.png)

**Comment by Fukki** [comment]
maybe problem from inventory update :/

**Comment by Foks5000** [comment]
hpPot, mpPot - these variables need to be reset when changing character

**Comment by Fukki** [comment]
add value reset when return to chracter screen
