### ISSUE TITLE
Error in PinkiePie's Proxy

### ISSUE THREAD

**Issue by AntiScrewdriver** [Fukki/auto-pot#9]
Hi Fukki, thank you for the great mod.
Just reporting an error =)

In PinkiePie's Proxy its causing this error
![autopoterror](https://user-images.githubusercontent.com/47073195/51796920-ab23d300-225f-11e9-9d70-cba931aa0b4b.jpg)

It's still working fine in Caali's proxy.

**Comment by Fukki** [comment]
because i design to Caali's proxy only
